# build and test on linux, windows, mac with node 12, 14, 16
name: integration-test

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

on:
  workflow_dispatch:
    inputs:
      vite_ref:
        description: 'vite git ref'
        required: true
        default: 'main'
      vite_plugin_svelte_ref:
        description: 'vite-plugin-svelte git ref'
        required: true
        default: 'main'
      sveltekit_ref:
        description: 'sveltekit git ref'
        required: true
        default: 'master'
jobs:
  integration-test:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [14]
        os: [ubuntu-latest]
    outputs:
      build_successful: ${{ steps.build.outcome == 'success' }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm i -g pnpm@6
      - name: 'checkout vite'
        uses: actions/checkout@v2
        with:
          repository: 'vitejs/vite'
          ref: '${{github.event.inputs.vite_ref}}'
          path: 'vite'
      - name: 'build and test vite'
        working-directory: 'vite'
        run: |
          pnpm install --frozen-lockfile
          pnpm run ci-build-vite
          pnpm run build-plugin-vue
          pnpm run build-plugin-react
          pnpm run test-serve -- --runInBand
          pnpm run test-build -- --runInBand
      - name: 'checkout vite-plugin-svelte'
        uses: actions/checkout@v2
        with:
          repository: 'sveltejs/vite-plugin-svelte'
          ref: '${{github.event.inputs.vite_plugin_svelte_ref}}'
          path: 'vite-plugin-svelte'
      - name: 'link local vite to vite-plugin-svelte'
        working-directory: 'vite-plugin-svelte'
        run: |
          mv package.json package.orig.json
          jq -r '.devDependencies.vite="${{github.workspace}}/vite/packages/vite"|.pnpm.overrides.vite="${{github.workspace}}/vite/packages/vite"' package.orig.json > package.json
          rm package.orig.json
      - name: 'build and test vite-plugin-svelte'
        working-directory: 'vite-plugin-svelte'
        run: |
          pnpm install --prefer-offline --ignore-scripts
          pnpm build:ci
          pnpm test:ci
      - name: 'checkout sveltekit'
        uses: actions/checkout@v2
        with:
          repository: 'sveltejs/kit'
          ref: '${{github.event.inputs.sveltekit_ref}}'
          path: 'kit'
      - name: 'link local vite and vite-plugin-svelte to sveltekit'
        working-directory: 'kit'
        run: |
          mv package.json package.orig.json
          jq -r '.devDependencies.vite="${{github.workspace}}/vite/packages/vite"|.pnpm.overrides.vite="${{github.workspace}}/vite/packages/vite"|.devDependencies."@sveltejs/vite-plugin-svelte"="${{github.workspace}}/vite-plugin-svelte/packages/vite-plugin-svelte"|.pnpm.overrides."@sveltejs/vite-plugin-svelte"="${{github.workspace}}/vite-plugin-svelte/packages/vite-plugin-svelte"' package.orig.json > package.json
          rm package.orig.json
      - name: 'build and test sveltekit'
        working-directory: 'kit'
        run: |
          pnpm install --prefer-offline
          pnpm build --filter ./packages --filter !./packages/create-svelte/templates
          pnpm test
